/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RosterTableRouteImport } from './routes/roster-table'
import { Route as QueryHealthRouteImport } from './routes/query-health'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiStudentsRouteImport } from './routes/api/students'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiAiEndpointRouteImport } from './routes/api/ai/$endpoint'

const RosterTableRoute = RosterTableRouteImport.update({
  id: '/roster-table',
  path: '/roster-table',
  getParentRoute: () => rootRouteImport,
} as any)
const QueryHealthRoute = QueryHealthRouteImport.update({
  id: '/query-health',
  path: '/query-health',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStudentsRoute = ApiStudentsRouteImport.update({
  id: '/api/students',
  path: '/api/students',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiEndpointRoute = ApiAiEndpointRouteImport.update({
  id: '/api/ai/$endpoint',
  path: '/api/ai/$endpoint',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/query-health': typeof QueryHealthRoute
  '/roster-table': typeof RosterTableRoute
  '/api/health': typeof ApiHealthRoute
  '/api/students': typeof ApiStudentsRoute
  '/api/ai/$endpoint': typeof ApiAiEndpointRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/query-health': typeof QueryHealthRoute
  '/roster-table': typeof RosterTableRoute
  '/api/health': typeof ApiHealthRoute
  '/api/students': typeof ApiStudentsRoute
  '/api/ai/$endpoint': typeof ApiAiEndpointRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/query-health': typeof QueryHealthRoute
  '/roster-table': typeof RosterTableRoute
  '/api/health': typeof ApiHealthRoute
  '/api/students': typeof ApiStudentsRoute
  '/api/ai/$endpoint': typeof ApiAiEndpointRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/query-health'
    | '/roster-table'
    | '/api/health'
    | '/api/students'
    | '/api/ai/$endpoint'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/query-health'
    | '/roster-table'
    | '/api/health'
    | '/api/students'
    | '/api/ai/$endpoint'
  id:
    | '__root__'
    | '/'
    | '/query-health'
    | '/roster-table'
    | '/api/health'
    | '/api/students'
    | '/api/ai/$endpoint'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  QueryHealthRoute: typeof QueryHealthRoute
  RosterTableRoute: typeof RosterTableRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiStudentsRoute: typeof ApiStudentsRoute
  ApiAiEndpointRoute: typeof ApiAiEndpointRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/roster-table': {
      id: '/roster-table'
      path: '/roster-table'
      fullPath: '/roster-table'
      preLoaderRoute: typeof RosterTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/query-health': {
      id: '/query-health'
      path: '/query-health'
      fullPath: '/query-health'
      preLoaderRoute: typeof QueryHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/students': {
      id: '/api/students'
      path: '/api/students'
      fullPath: '/api/students'
      preLoaderRoute: typeof ApiStudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/$endpoint': {
      id: '/api/ai/$endpoint'
      path: '/api/ai/$endpoint'
      fullPath: '/api/ai/$endpoint'
      preLoaderRoute: typeof ApiAiEndpointRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  QueryHealthRoute: QueryHealthRoute,
  RosterTableRoute: RosterTableRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiStudentsRoute: ApiStudentsRoute,
  ApiAiEndpointRoute: ApiAiEndpointRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
