/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RosterTableRouteImport } from './routes/roster-table'
import { Route as QueryHealthRouteImport } from './routes/query-health'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppPageRouteImport } from './routes/app.$page'
import { Route as ApiStudentsHierarchyRouteImport } from './routes/api/students-hierarchy'
import { Route as ApiStudentsRouteImport } from './routes/api/students'
import { Route as ApiSchoolsRouteImport } from './routes/api/schools'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiDashboardRouteImport } from './routes/api/dashboard'
import { Route as ApiAuditRouteImport } from './routes/api/audit'
import { Route as ApiExperimentsLandingEventsRouteImport } from './routes/api/experiments/landing-events'
import { Route as ApiExperimentsLandingRouteImport } from './routes/api/experiments/landing'
import { Route as ApiDataDomainRouteImport } from './routes/api/data/$domain'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as ApiAuthCallbackRouteImport } from './routes/api/auth/callback'
import { Route as ApiAiEndpointRouteImport } from './routes/api/ai/$endpoint'

const RosterTableRoute = RosterTableRouteImport.update({
  id: '/roster-table',
  path: '/roster-table',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/roster-table.lazy').then((d) => d.Route))
const QueryHealthRoute = QueryHealthRouteImport.update({
  id: '/query-health',
  path: '/query-health',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/query-health.lazy').then((d) => d.Route))
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/app.lazy').then((d) => d.Route))
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const AppPageRoute = AppPageRouteImport.update({
  id: '/$page',
  path: '/$page',
  getParentRoute: () => AppRoute,
} as any).lazy(() => import('./routes/app.$page.lazy').then((d) => d.Route))
const ApiStudentsHierarchyRoute = ApiStudentsHierarchyRouteImport.update({
  id: '/api/students-hierarchy',
  path: '/api/students-hierarchy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStudentsRoute = ApiStudentsRouteImport.update({
  id: '/api/students',
  path: '/api/students',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSchoolsRoute = ApiSchoolsRouteImport.update({
  id: '/api/schools',
  path: '/api/schools',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDashboardRoute = ApiDashboardRouteImport.update({
  id: '/api/dashboard',
  path: '/api/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuditRoute = ApiAuditRouteImport.update({
  id: '/api/audit',
  path: '/api/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExperimentsLandingEventsRoute =
  ApiExperimentsLandingEventsRouteImport.update({
    id: '/api/experiments/landing-events',
    path: '/api/experiments/landing-events',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiExperimentsLandingRoute = ApiExperimentsLandingRouteImport.update({
  id: '/api/experiments/landing',
  path: '/api/experiments/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDataDomainRoute = ApiDataDomainRouteImport.update({
  id: '/api/data/$domain',
  path: '/api/data/$domain',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthCallbackRoute = ApiAuthCallbackRouteImport.update({
  id: '/api/auth/callback',
  path: '/api/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiEndpointRoute = ApiAiEndpointRouteImport.update({
  id: '/api/ai/$endpoint',
  path: '/api/ai/$endpoint',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/query-health': typeof QueryHealthRoute
  '/roster-table': typeof RosterTableRoute
  '/api/audit': typeof ApiAuditRoute
  '/api/dashboard': typeof ApiDashboardRoute
  '/api/health': typeof ApiHealthRoute
  '/api/schools': typeof ApiSchoolsRoute
  '/api/students': typeof ApiStudentsRoute
  '/api/students-hierarchy': typeof ApiStudentsHierarchyRoute
  '/app/$page': typeof AppPageRoute
  '/api/ai/$endpoint': typeof ApiAiEndpointRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/data/$domain': typeof ApiDataDomainRoute
  '/api/experiments/landing': typeof ApiExperimentsLandingRoute
  '/api/experiments/landing-events': typeof ApiExperimentsLandingEventsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/query-health': typeof QueryHealthRoute
  '/roster-table': typeof RosterTableRoute
  '/api/audit': typeof ApiAuditRoute
  '/api/dashboard': typeof ApiDashboardRoute
  '/api/health': typeof ApiHealthRoute
  '/api/schools': typeof ApiSchoolsRoute
  '/api/students': typeof ApiStudentsRoute
  '/api/students-hierarchy': typeof ApiStudentsHierarchyRoute
  '/app/$page': typeof AppPageRoute
  '/api/ai/$endpoint': typeof ApiAiEndpointRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/data/$domain': typeof ApiDataDomainRoute
  '/api/experiments/landing': typeof ApiExperimentsLandingRoute
  '/api/experiments/landing-events': typeof ApiExperimentsLandingEventsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/query-health': typeof QueryHealthRoute
  '/roster-table': typeof RosterTableRoute
  '/api/audit': typeof ApiAuditRoute
  '/api/dashboard': typeof ApiDashboardRoute
  '/api/health': typeof ApiHealthRoute
  '/api/schools': typeof ApiSchoolsRoute
  '/api/students': typeof ApiStudentsRoute
  '/api/students-hierarchy': typeof ApiStudentsHierarchyRoute
  '/app/$page': typeof AppPageRoute
  '/api/ai/$endpoint': typeof ApiAiEndpointRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/data/$domain': typeof ApiDataDomainRoute
  '/api/experiments/landing': typeof ApiExperimentsLandingRoute
  '/api/experiments/landing-events': typeof ApiExperimentsLandingEventsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/query-health'
    | '/roster-table'
    | '/api/audit'
    | '/api/dashboard'
    | '/api/health'
    | '/api/schools'
    | '/api/students'
    | '/api/students-hierarchy'
    | '/app/$page'
    | '/api/ai/$endpoint'
    | '/api/auth/callback'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/data/$domain'
    | '/api/experiments/landing'
    | '/api/experiments/landing-events'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/query-health'
    | '/roster-table'
    | '/api/audit'
    | '/api/dashboard'
    | '/api/health'
    | '/api/schools'
    | '/api/students'
    | '/api/students-hierarchy'
    | '/app/$page'
    | '/api/ai/$endpoint'
    | '/api/auth/callback'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/data/$domain'
    | '/api/experiments/landing'
    | '/api/experiments/landing-events'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/query-health'
    | '/roster-table'
    | '/api/audit'
    | '/api/dashboard'
    | '/api/health'
    | '/api/schools'
    | '/api/students'
    | '/api/students-hierarchy'
    | '/app/$page'
    | '/api/ai/$endpoint'
    | '/api/auth/callback'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/data/$domain'
    | '/api/experiments/landing'
    | '/api/experiments/landing-events'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  QueryHealthRoute: typeof QueryHealthRoute
  RosterTableRoute: typeof RosterTableRoute
  ApiAuditRoute: typeof ApiAuditRoute
  ApiDashboardRoute: typeof ApiDashboardRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiSchoolsRoute: typeof ApiSchoolsRoute
  ApiStudentsRoute: typeof ApiStudentsRoute
  ApiStudentsHierarchyRoute: typeof ApiStudentsHierarchyRoute
  ApiAiEndpointRoute: typeof ApiAiEndpointRoute
  ApiAuthCallbackRoute: typeof ApiAuthCallbackRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiDataDomainRoute: typeof ApiDataDomainRoute
  ApiExperimentsLandingRoute: typeof ApiExperimentsLandingRoute
  ApiExperimentsLandingEventsRoute: typeof ApiExperimentsLandingEventsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/roster-table': {
      id: '/roster-table'
      path: '/roster-table'
      fullPath: '/roster-table'
      preLoaderRoute: typeof RosterTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/query-health': {
      id: '/query-health'
      path: '/query-health'
      fullPath: '/query-health'
      preLoaderRoute: typeof QueryHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/$page': {
      id: '/app/$page'
      path: '/$page'
      fullPath: '/app/$page'
      preLoaderRoute: typeof AppPageRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/students-hierarchy': {
      id: '/api/students-hierarchy'
      path: '/api/students-hierarchy'
      fullPath: '/api/students-hierarchy'
      preLoaderRoute: typeof ApiStudentsHierarchyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/students': {
      id: '/api/students'
      path: '/api/students'
      fullPath: '/api/students'
      preLoaderRoute: typeof ApiStudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/schools': {
      id: '/api/schools'
      path: '/api/schools'
      fullPath: '/api/schools'
      preLoaderRoute: typeof ApiSchoolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dashboard': {
      id: '/api/dashboard'
      path: '/api/dashboard'
      fullPath: '/api/dashboard'
      preLoaderRoute: typeof ApiDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/audit': {
      id: '/api/audit'
      path: '/api/audit'
      fullPath: '/api/audit'
      preLoaderRoute: typeof ApiAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/experiments/landing-events': {
      id: '/api/experiments/landing-events'
      path: '/api/experiments/landing-events'
      fullPath: '/api/experiments/landing-events'
      preLoaderRoute: typeof ApiExperimentsLandingEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/experiments/landing': {
      id: '/api/experiments/landing'
      path: '/api/experiments/landing'
      fullPath: '/api/experiments/landing'
      preLoaderRoute: typeof ApiExperimentsLandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/data/$domain': {
      id: '/api/data/$domain'
      path: '/api/data/$domain'
      fullPath: '/api/data/$domain'
      preLoaderRoute: typeof ApiDataDomainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/callback': {
      id: '/api/auth/callback'
      path: '/api/auth/callback'
      fullPath: '/api/auth/callback'
      preLoaderRoute: typeof ApiAuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/$endpoint': {
      id: '/api/ai/$endpoint'
      path: '/api/ai/$endpoint'
      fullPath: '/api/ai/$endpoint'
      preLoaderRoute: typeof ApiAiEndpointRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppPageRoute: typeof AppPageRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppPageRoute: AppPageRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  QueryHealthRoute: QueryHealthRoute,
  RosterTableRoute: RosterTableRoute,
  ApiAuditRoute: ApiAuditRoute,
  ApiDashboardRoute: ApiDashboardRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiSchoolsRoute: ApiSchoolsRoute,
  ApiStudentsRoute: ApiStudentsRoute,
  ApiStudentsHierarchyRoute: ApiStudentsHierarchyRoute,
  ApiAiEndpointRoute: ApiAiEndpointRoute,
  ApiAuthCallbackRoute: ApiAuthCallbackRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiDataDomainRoute: ApiDataDomainRoute,
  ApiExperimentsLandingRoute: ApiExperimentsLandingRoute,
  ApiExperimentsLandingEventsRoute: ApiExperimentsLandingEventsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
