/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RosterTableRouteImport } from './routes/roster-table'
import { Route as QueryHealthRouteImport } from './routes/query-health'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppPageRouteImport } from './routes/app.$page'
import { Route as ApiStudentsRouteImport } from './routes/api/students'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as ApiAuthCallbackRouteImport } from './routes/api/auth/callback'
import { Route as ApiAiEndpointRouteImport } from './routes/api/ai/$endpoint'

const RosterTableRoute = RosterTableRouteImport.update({
  id: '/roster-table',
  path: '/roster-table',
  getParentRoute: () => rootRouteImport,
} as any)
const QueryHealthRoute = QueryHealthRouteImport.update({
  id: '/query-health',
  path: '/query-health',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPageRoute = AppPageRouteImport.update({
  id: '/$page',
  path: '/$page',
  getParentRoute: () => AppRoute,
} as any)
const ApiStudentsRoute = ApiStudentsRouteImport.update({
  id: '/api/students',
  path: '/api/students',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthCallbackRoute = ApiAuthCallbackRouteImport.update({
  id: '/api/auth/callback',
  path: '/api/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiEndpointRoute = ApiAiEndpointRouteImport.update({
  id: '/api/ai/$endpoint',
  path: '/api/ai/$endpoint',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/query-health': typeof QueryHealthRoute
  '/roster-table': typeof RosterTableRoute
  '/api/health': typeof ApiHealthRoute
  '/api/students': typeof ApiStudentsRoute
  '/app/$page': typeof AppPageRoute
  '/api/ai/$endpoint': typeof ApiAiEndpointRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/query-health': typeof QueryHealthRoute
  '/roster-table': typeof RosterTableRoute
  '/api/health': typeof ApiHealthRoute
  '/api/students': typeof ApiStudentsRoute
  '/app/$page': typeof AppPageRoute
  '/api/ai/$endpoint': typeof ApiAiEndpointRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/query-health': typeof QueryHealthRoute
  '/roster-table': typeof RosterTableRoute
  '/api/health': typeof ApiHealthRoute
  '/api/students': typeof ApiStudentsRoute
  '/app/$page': typeof AppPageRoute
  '/api/ai/$endpoint': typeof ApiAiEndpointRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/query-health'
    | '/roster-table'
    | '/api/health'
    | '/api/students'
    | '/app/$page'
    | '/api/ai/$endpoint'
    | '/api/auth/callback'
    | '/api/auth/login'
    | '/api/auth/logout'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/query-health'
    | '/roster-table'
    | '/api/health'
    | '/api/students'
    | '/app/$page'
    | '/api/ai/$endpoint'
    | '/api/auth/callback'
    | '/api/auth/login'
    | '/api/auth/logout'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/query-health'
    | '/roster-table'
    | '/api/health'
    | '/api/students'
    | '/app/$page'
    | '/api/ai/$endpoint'
    | '/api/auth/callback'
    | '/api/auth/login'
    | '/api/auth/logout'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  QueryHealthRoute: typeof QueryHealthRoute
  RosterTableRoute: typeof RosterTableRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiStudentsRoute: typeof ApiStudentsRoute
  ApiAiEndpointRoute: typeof ApiAiEndpointRoute
  ApiAuthCallbackRoute: typeof ApiAuthCallbackRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/roster-table': {
      id: '/roster-table'
      path: '/roster-table'
      fullPath: '/roster-table'
      preLoaderRoute: typeof RosterTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/query-health': {
      id: '/query-health'
      path: '/query-health'
      fullPath: '/query-health'
      preLoaderRoute: typeof QueryHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/$page': {
      id: '/app/$page'
      path: '/$page'
      fullPath: '/app/$page'
      preLoaderRoute: typeof AppPageRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/students': {
      id: '/api/students'
      path: '/api/students'
      fullPath: '/api/students'
      preLoaderRoute: typeof ApiStudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/callback': {
      id: '/api/auth/callback'
      path: '/api/auth/callback'
      fullPath: '/api/auth/callback'
      preLoaderRoute: typeof ApiAuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/$endpoint': {
      id: '/api/ai/$endpoint'
      path: '/api/ai/$endpoint'
      fullPath: '/api/ai/$endpoint'
      preLoaderRoute: typeof ApiAiEndpointRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppPageRoute: typeof AppPageRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppPageRoute: AppPageRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  QueryHealthRoute: QueryHealthRoute,
  RosterTableRoute: RosterTableRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiStudentsRoute: ApiStudentsRoute,
  ApiAiEndpointRoute: ApiAiEndpointRoute,
  ApiAuthCallbackRoute: ApiAuthCallbackRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
